server:
  port: 8180
  servlet:
    context-path: /app

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ONLINE_SHOP
    username: root1
    password: root1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/